### ISSUE TITLE
error with npm start

### ISSUE THREAD

**Issue by daledali** [Gabsii/spoti-vote#180]
**Describe the bug**
After entering npm start I get this error

**To Reproduce**

**Expected behavior**
it should work

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10
 - Browser [e.g. chrome, safari] edge dev and chrome

0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start'
1 verbose cli ]
2 info using npm@6.13.4
3 info using node@v12.16.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle spoti-vote@1.0.1~prestart: spoti-vote@1.0.1
6 info lifecycle spoti-vote@1.0.1~start: spoti-vote@1.0.1
7 verbose lifecycle spoti-vote@1.0.1~start: unsafe-perm in lifecycle true
8 verbose lifecycle spoti-vote@1.0.1~start: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\mydjt\spoti-vote\node_modules\.bin;"C:\Program Files (x86)\Common Files\Oracle\Java\javapath\;C:\cygwin64\bin\";C:\ProgramData\scoop\shims;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\iCLS\;C:\Program Files\Intel\Intel(R) Management Engine Components\iCLS\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Docker\Docker\resources\bin;C:\ProgramData\DockerDesktop\version-bin;C:\ProgramData\chocolatey\bin;C:\Program Files (x86)\Calibre2\;C:\Program Files\PuTTY\;C:\Program Files\Amazon\AWSCLIV2\;C:\Go\bin;D:\GYB\;C:\Users\mydjt\AppData\Roaming\nvm;C:\Program Files\nodejs;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files\nodejs\;c:\jruby-9.2.10.0\bin;C:\Users\mydjt\scoop\apps\python\current;C:\Users\mydjt\scoop\apps\python\current\Scripts;C:\Users\mydjt\scoop\shims;C:\Users\mydjt\AppData\Local\Microsoft\WindowsApps;C:\Program Files\heroku\bin;C:\Users\mydjt\go\bin;C:\Users\mydjt\AppData\Roaming\nvm;C:\Program Files\nodejs;C:\Users\mydjt\AppData\Local\atom\bin;C:\Users\mydjt\AppData\Roaming\npm
9 verbose lifecycle spoti-vote@1.0.1~start: CWD: C:\Users\mydjt\spoti-vote
10 silly lifecycle spoti-vote@1.0.1~start: Args: [
10 silly lifecycle   '/d /s /c',
10 silly lifecycle   'concurrently --kill-others-on-fail "npm:start-frontend" "npm:start-backend"'
10 silly lifecycle ]
11 silly lifecycle spoti-vote@1.0.1~start: Returned: code: 1  signal: null
12 info lifecycle spoti-vote@1.0.1~start: Failed to exec start script
13 verbose stack Error: spoti-vote@1.0.1 start: `concurrently --kill-others-on-fail "npm:start-frontend" "npm:start-backend"`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:311:20)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:311:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid spoti-vote@1.0.1
15 verbose cwd C:\Users\mydjt\spoti-vote
16 verbose Windows_NT 10.0.19041
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
18 verbose node v12.16.1
19 verbose npm  v6.13.4
20 error code ELIFECYCLE
21 error errno 1
22 error spoti-vote@1.0.1 start: `concurrently --kill-others-on-fail "npm:start-frontend" "npm:start-backend"`
22 error Exit status 1
23 error Failed at the spoti-vote@1.0.1 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Additional context**

**Comment by daledali** [comment]
I entered my login and password. Signed up for a developer account problem solved.
