### ISSUE TITLE
Backend doesn't work "exit code 0"

### ISSUE THREAD

**Issue by thomasesr** [Gabsii/spoti-vote#273]
can't start backend, it doesn't show any errors just exit code 0 and will not serve anything on the backend port.
When I try to start a party it just says connection refused. I tried every node version, followed the README to the letter and still nothing.

```
~/spoti-vote# npm run start-backend --verbose
npm verb cli [
npm verb cli   '/root/.nvm/versions/node/v15.14.0/bin/node',
npm verb cli   '/root/.nvm/versions/node/v15.14.0/bin/npm',
npm verb cli   'run',
npm verb cli   'start-backend',
npm verb cli   '--verbose'
npm verb cli ]
npm info using npm@7.7.6
npm info using node@v15.14.0
npm timing npm:load:whichnode Completed in 1ms
npm timing config:load:defaults Completed in 2ms
npm timing config:load:file:/root/.nvm/versions/node/v15.14.0/lib/node_modules/npm/npmrc Completed in 1ms
npm timing config:load:builtin Completed in 1ms
npm timing config:load:cli Completed in 2ms
npm timing config:load:env Completed in 0ms
npm timing config:load:file:/root/spoti-vote/.npmrc Completed in 0ms
npm timing config:load:project Completed in 1ms
npm timing config:load:file:/root/.npmrc Completed in 0ms
npm timing config:load:user Completed in 0ms
npm timing config:load:file:/root/.nvm/versions/node/v15.14.0/etc/npmrc Completed in 0ms
npm timing config:load:global Completed in 0ms
npm timing config:load:validate Completed in 1ms
npm timing config:load:setEnvs Completed in 1ms
npm timing config:load Completed in 8ms
npm timing npm:load:configload Completed in 8ms
npm timing npm:load:setTitle Completed in 0ms
npm timing npm:load:setupLog Completed in 2ms
npm timing npm:load:cleanupLog Completed in 3ms
npm timing npm:load:configScope Completed in 0ms
npm timing npm:load:projectScope Completed in 1ms
npm timing npm:load Completed in 20ms
npm timing config:load:flatten Completed in 4ms
[..................] | : timing config:load:flatten Completed in 4ms
> spoti-vote@1.0.2 start-backend
> dotenv -- cross-var vercel dev ./backend -l %PORTBACK%

npm timing command:run-script Completed in 519ms
npm verb exit 0
npm timing npm Completed in 708ms
npm info ok 

```

**Comment by Michiocre** [comment]
The readme is not very up to date, in order for the backend to work you have to install the [vercel cli](https://vercel.com/cli).
Then also run `vercel login`.

**Comment by Michiocre** [comment]
In case you dont want to use vercel, I just created a new branch called `newServer`  that only relies on express for the backend.
(This branch still has a lot of issues when it comes to displaying data correctly on the frontend).

There is a new readme on that branch as well.

**Comment by thomasesr** [comment]
I tried using vercel on the master branch and it still doesn't work. Now I cant get the backend to run but now I get a 502 error:

```
Unhandled rejection: TypeError: helper.createServerWithHelpers is not a function
    at /home/username/.nvm/versions/node/v14.8.0/lib/node_modules/vercel/node_modules/@vercel/node/dist/launcher.js:89:37
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
Error! Failed to complete request to /api/login: Error: read ECONNRESET
```

I did try to use the newServer branch and was successful in starting the backend server but I can't select a playlist (no playlist shows up on the dropdown menu) I can change volume and skip and pause songs.

**Comment by thomasesr** [comment]
after restarting the backend and frontend I can now see the playlists.
